version: '3.8'
services:
  db:
    container_name: stockuprb_postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5433"
  api:
    container_name: stockuprb
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    volumes:
      - .:/stockuprb-api
    ports:
      - "4000:4000"
    depends_on:
      - db
volumes:
  postgres: