require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/v1/agreements", type: :request do
  let (:user) { create_user }
  let (:organisation) { create :organisation }
  let (:company) { create :company}
  # This should return the minimal set of attributes required to create a valid
  # Agreement. As you add validations to Agreement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {company_id: company.id, start_at: DateTime.now() - 5.months, end_at: nil, name: "012/0303/9293"}
  }

  let(:invalid_attributes) {
    {start_at: DateTime.now() - 5.months, end_at: nil, name: nil}
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # AgreementsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    before do
      login_with_api(user)
      # puts "#{response.headers['Authorization']}"
    end
    it "renders a successful response" do
      Agreement.create! valid_attributes
      get "/v1/agreements", headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      agreement = Agreement.create! valid_attributes
      get "/v1/agreements", as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Agreement" do
        expect {
          post "/v1/agreements",
               params: { agreement: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Agreement, :count).by(1)
      end

      it "renders a JSON response with the new agreement" do
        post "/v1/agreements",
             params: { agreement: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Agreement" do
        expect {
          post "/v1/agreements",
               params: { agreement: invalid_attributes }, as: :json
        }.to change(Agreement, :count).by(0)
      end

      it "renders a JSON response with errors for the new agreement" do
        post "/v1/agreements",
             params: { agreement: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json; charset=utf-8")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {end_at: DateTime.now() + 1.months}
      }

      it "updates the requested agreement" do
        agreement = Agreement.create! valid_attributes
        patch "/v1/agreements/#{agreement.id}",
              params: { agreement: new_attributes }, headers: valid_headers, as: :json
        agreement.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the agreement" do
        agreement = Agreement.create! valid_attributes
        patch "/v1/agreements/#{agreement.id}",
              params: { agreement: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the agreement" do
        agreement = Agreement.create! valid_attributes
        patch "/v1/agreements/#{agreement.id}",
              params: { agreement: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json; charset=utf-8")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested agreement" do
      agreement = Agreement.create! valid_attributes
      expect {
        delete "/v1/agreements/#{agreement.id}", headers: valid_headers, as: :json
      }.to change(Agreement, :count).by(-1)
    end
  end
end
