require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/v1/bank_accounts', type: :request do
  let (:user) { create_user }
  let (:organisation) { create :organisation }
  # This should return the minimal set of attributes required to create a valid
  # BankAccount. As you add validations to BankAccount, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { name: 'Test Bank Account', details: { inn: '123456789' } }
  end

  let(:invalid_attributes) do
    { name: nil, details: { inn: '123456789' } }
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # BankAccountsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    {}
  end

  describe 'GET /index' do
    before do
      login_with_api(user)
      get "/v1/users/#{user.id}", headers: {
        'Authorization': response.headers['Authorization']
      }
    end
    it 'renders a successful response' do
      organisation.bank_accounts.create! valid_attributes
      get "/v1/organisations/#{organisation.id}/bank_accounts", headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      bank_account = organisation.bank_accounts.create! valid_attributes
      get "/v1/organisations/#{organisation.id}/bank_accounts/#{bank_account.id}",  as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new BankAccount' do
        expect do
          post "/v1/organisations/#{organisation.id}/bank_accounts",
               params: { bank_account: valid_attributes }, headers: valid_headers, as: :json
        end.to change(BankAccount, :count).by(1)
      end

      it 'renders a JSON response with the new bank_account' do
        post "/v1/organisations/#{organisation.id}/bank_accounts",
             params: { bank_account: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new BankAccount' do
        expect do
          post "/v1/organisations/#{organisation.id}/bank_accounts",
               params: { bank_account: invalid_attributes }, as: :json
        end.to change(BankAccount, :count).by(0)
      end

      it 'renders a JSON response with errors for the new bank_account' do
        post "/v1/organisations/#{organisation.id}/bank_accounts",
             params: { bank_account: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { name: 'ReTest Bank Account', details: { inn: '123456789', kpp: '987654321' } }
      }

      it "updates the requested bank_account" do
        bank_account = organisation.bank_accounts.create! valid_attributes
        patch "/v1/organisations/#{organisation.id}/bank_accounts/#{bank_account.id}",
              params: { bank_account: new_attributes }, headers: valid_headers, as: :json
        bank_account.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the bank_account" do
        bank_account = organisation.bank_accounts.create! valid_attributes
        patch "/v1/organisations/#{organisation.id}/bank_accounts/#{bank_account.id}",
              params: { bank_account: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the bank_account" do
        bank_account = organisation.bank_accounts.create! valid_attributes
        patch "/v1/organisations/#{organisation.id}/bank_accounts/#{bank_account.id}",
              params: { bank_account: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bank_account" do
      bank_account = organisation.bank_accounts.create! valid_attributes
      expect {
        delete "/v1/organisations/#{organisation.id}/bank_accounts/#{bank_account.id}", headers: valid_headers, as: :json
      }.to change(BankAccount, :count).by(-1)
    end
  end
end
