require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/v1/vat_rates", type: :request do
  let (:user) { create_user }
  # This should return the minimal set of attributes required to create a valid
  # VatRate. As you add validations to VatRate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { rate: 20, name: '20%' }
  }

  let(:invalid_attributes) {
    { rate: nil, name: nil }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # VatRatesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    before do
      login_with_api(user)
      get "/v1/users/#{user.id}", headers: {
        'Authorization': response.headers['Authorization']
      }
    end
    it "renders a successful response" do
      VatRate.create! valid_attributes
      get v1_vat_rates_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      vat_rate = VatRate.create! valid_attributes
      get v1_vat_rate_url(vat_rate), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new VatRate" do
        expect {
          post v1_vat_rates_url,
               params: { vat_rate: valid_attributes }, headers: valid_headers, as: :json
        }.to change(VatRate, :count).by(1)
      end

      it "renders a JSON response with the new vat_rate" do
        post v1_vat_rates_url,
             params: { vat_rate: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new VatRate" do
        expect {
          post v1_vat_rates_url,
               params: { vat_rate: invalid_attributes }, as: :json
        }.to change(VatRate, :count).by(0)
      end

      it "renders a JSON response with errors for the new vat_rate" do
        post v1_vat_rates_url,
             params: { vat_rate: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { rate: 10, name: '10%' }
      }

      it "updates the requested vat_rate" do
        vat_rate = VatRate.create! valid_attributes
        patch v1_vat_rate_url(vat_rate),
              params: { vat_rate: new_attributes }, headers: valid_headers, as: :json
        vat_rate.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the vat_rate" do
        vat_rate = VatRate.create! valid_attributes
        patch v1_vat_rate_url(vat_rate),
              params: { vat_rate: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the vat_rate" do
        vat_rate = VatRate.create! valid_attributes
        patch v1_vat_rate_url(vat_rate),
              params: { vat_rate: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested vat_rate" do
      vat_rate = VatRate.create! valid_attributes
      expect {
        delete v1_vat_rate_url(vat_rate), headers: valid_headers, as: :json
      }.to change(VatRate, :count).by(-1)
    end
  end
end
