---
    get:
      description: List of Products
      tags:
      - Products
      parameters:
      - name: page
        in: query
        type: number
        required: false
        description: Page number
      - name: limit
        in: query
        schema:
          type: number
        required: false
        description: Limit on page
      - name: sort
        in: query
        schema:
          type: string
          default: name
        required: false
        description: Attribute for sort
      - name: direction
        in: query
        schema:
          type: string
          default: desc
          enum:
            - asc
            - desc
        required: false
        description: Sort direction
      - name: search
        in: query
        schema:
          type: string
        required: false
        description: Search by name, sku, description
      responses:
        '200':
          description: List of Invoices
    
